### ISSUE TITLE
Ruby on Rails Group Capstone: Kanban Board Setup

### ISSUE THREAD

**Issue by PraisesPJMT** [PraisesPJMT/FoodPad-App#11]
## Project Link
- Project Kanban Link: [https://github.com/users/PraisesPJMT/projects/9](https://github.com/users/PraisesPJMT/projects/9)
- Repository Link: [https://github.com/PraisesPJMT/FoodPad-App](https://github.com/PraisesPJMT/FoodPad-App)

## Team Members
Here are the team members working on this project.
- Member 1: Paul Onchera (@Paul-js-hub)
- Member 2: Praises Tula (@PraisesPJMT)

## Team Tasks
This is how project tasks are distributed to team members.
- Group Task: Tasks #2, #3, #10
- Member 1 (@Paul-js-hub): Tasks #4, #6, #8
- Member 2 (@PraisesPJMT): Tasks #1, #5, #7, #9

Happy Reviewing!!!!

**Comment by KDlamini** [comment]
### Hi team @PraisesPJMT, @Paul-js-hub 🙋‍♀️,  

Excellent work! 💯 
You have done a great job creating a Kanban Board for the Recipe App. 
Your feature is complete!
Congratulations!!!🎊 🥳 

## Highlights 🌞 

✔️  Board has To Do, In Progress, In Review, and Done columns
✔️  Tasks have assigned members with points and a descriptive title
✔️  Tasks are distributed in a fair way

# Status: Approved ✔️ 

![giphyapproved](https://user-images.githubusercontent.com/38088818/152676874-3b2edc2c-a46f-4da6-b253-be859d2a2c65.gif)
 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by PraisesPJMT** [comment]
Thanks you so much @KDlamini for the amazing review and feedback!
